app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: "."
    type:     "api"
    prefix:   "/api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
   path: /api/login_check