services:
    resource.person.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { username: "exact" } ]
    resource.person:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Person" ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.person.search_filter" ] ]
        tags:      [ { name: "api.resource" } ]

    resource.stats:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Stats" ]
        tags:      [ { name: "api.resource" } ]